### ISSUE TITLE
add tip jar

### ISSUE THREAD

**Issue by postprivee** [penghuili/PreCloud#3]
could you maybe add a tip jar as iap purchase to support the development 
-for those not using paypal-

**Comment by penghuili** [comment]
Thank you for the offer! I will add it soon.

It may take some time though, I have never worked with iap, but hopefully will be done this year.

I will update you here.

**Comment by penghuili** [comment]
Hey @postprivee , in the latest release (version 1.13.0), you can find donate with iap now
Turns out it's quite easy to implement this :)

**Comment by postprivee** [comment]
@penghuili glad to hear! thanks!
